name: Automatically create release Pull request for merging develop into master.
on:
  push:
    branches:
      - 'master'
jobs:
  github_release_pr:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a pull request for merging develop into master.
        uses: peter-evans/create-pull-request@v4
      - name: Slack Notification after PR is ready for review.
        uses: kv109/action-ready-for-review@0.1
        env:
          SLACK_CHANNEL: 'cloud'
          SLACk_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}         
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 
        with:
          args: '{\"channel\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 
