name: Automatically create release Pull request for merging develop into master.
on:
  push:
    branches:
      - 'master'
jobs:
  github_release_pr:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a pull request for merging develop into master.
        uses: peter-evans/create-pull-request@v4
      - name: Slack Notification after PR is ready for review.
        uses: kv109/action-ready-for-review@0.1
        env:
          SLACK_CHANNEL: 'cloud'
          SLACk_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}         
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: 'New PR created and waits for your approval ' 
