name: Automatically create release Pull request for merging develop into master.
on:
  push:
    branches:
      - 'master'
jobs:
  github_release_pr:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a pull request for merging develop into master.
        uses: peter-evans/create-pull-request@v4
      - name: Slack Notification after PR is ready for review.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_TITLE: 'NEW Pull Request is ready for Review!'
          SLACK_MESSAGE: 'A Pull Request needs your approval before merging to Master branch.'
         
